hmrc/catalogue-frontend

README.md
test/uk/gov/hmrc/cataloguefrontend/ServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/TeamsSpec.scala

- Test fixes
- Test info added to README.md
@agilestevesmith

Platops 576 test fixes

---

.gitignore
app/assets/catalogue-frontend.scss
app/views/team_info.scala.html
public/catalogue-frontend.css

Tweaks to align the look and feel of the page

Fe 276 alignment tweaks

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/TeamsAndRepositoriesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/service/LeakDetectionService.scala
app/views/library_info.scala.html
app/views/prototype_info.scala.html
app/views/repository_info.scala.html
app/views/service_info.scala.html
conf/application.conf
test/uk/gov/hmrc/cataloguefrontend/DependencyReportControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DeploymentsServiceSpec.scala
test/uk/gov/hmrc/cataloguefrontend/SearchFilteringSpec.scala
test/uk/gov/hmrc/cataloguefrontend/TeamServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/TeamsAndRepositoriesConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/LeakDetectionServiceSpec.scala

Replaces lookup of owningTeams with a static configuration

Don't show LDS banners for shared repos

---

app/views/ServiceConfigPage.scala.html

Changed the way the test finds elements to help with different browser/driver behaviours.

fix: Handle browser/driver behaviours

---

app/uk/gov/hmrc/cataloguefrontend/service/RouteRulesService.scala
app/views/partials/details.scala.html
app/views/partials/serviceRouteRuleViolations.scala.html
test/uk/gov/hmrc/cataloguefrontend/service/RouteRulesServiceSpec.scala
test/view/partials/CodeAndBuildsSpec.scala
test/view/partials/DetailsSpec.scala
test/view/partials/ServiceRouteRuleViolationsSpec.scala

Remove link ability for different environments and improve inconsistent route rules information display.

fix: Remove link ability for different environments

---

app/uk/gov/hmrc/cataloguefrontend/shuttering/ShutterLinkUtils.scala
test/uk/gov/hmrc/cataloguefrontend/shuttering/ShutterLinkUtilsSpec.scala

URL needs "www." to work in some environments

BDOG-480 Fixes URL

---

app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model.scala
app/views/WhatsRunningWherePage.scala.html
app/views/standard_layout.scala.html
conf/app.routes
test/uk/gov/hmrc/cataloguefrontend/connector/ReleasesConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model/EnvironmentOrderingSpec.scala

Profile filter can be done via the query params, but there's another
ticket somewhere to do profiles properly so haven't completed that bit
yet.
The application-name filtering is only via JavaScript, as there are a
few UX behaviours that feel weird with the current way we filter
server-side. I will spend a bit of time trying to form a model for how
we do this nicely...
Screenshot available on the JIRA.

BDOG-447: Filtering, mainly by App Name

---

app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereService.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model.scala
conf/app.routes
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereSpec.scala

Basic functionality to start with: a copy of WhatsRunningWhere, but just for ECS.
Lots more work, and refactoring, to come.

BDOG-521: Show ECS releases in Catalogue

---

app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model.scala

Anticipating that the ordering will reverse in the near future, but
that can wait.

BDOG-521: Ordering for ECS WhatsRunningWhere

---

app/views/partials/githubBadgeType.scala
test/view/partials/GithubBadgeTypeSpec.scala

This is suggested by @chotai in the JIRA ticket . Happy to close this PR if people don't approve of this change.

BDOG-1007: Changed github label from Open to Public

---

app/views/DependencyExplorerPage.scala.html
app/views/standard_layout.scala.html

Uncaught TypeError: list.list is undefined
list.js is doing stuff, and cannot find the class it needs in the DOM.

Stop JS error on dependency explorer (when zero results)

---

app/uk/gov/hmrc/cataloguefrontend/metrics/connector/MetricsConnector.scala
app/uk/gov/hmrc/cataloguefrontend/metrics/model/ServiceMetricsEntry.scala
app/uk/gov/hmrc/cataloguefrontend/metrics/views/MetricsDisplayPage.scala.html
conf/app.routes

minor refactor of metrics overview

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ResourceUsageConnector.scala
app/uk/gov/hmrc/cataloguefrontend/model/Environment.scala
app/uk/gov/hmrc/cataloguefrontend/service/CostEstimationService.scala
app/uk/gov/hmrc/cataloguefrontend/util/ChartDataTable.scala
app/views/CostEstimationPage.scala.html
app/views/ServiceInfoPage.scala.html
app/views/partials/costEstimation.scala.html
conf/app.routes
test/uk/gov/hmrc/cataloguefrontend/DigitalServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/LibrariesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/PrototypesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ResourceUsageConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/CostEstimationServiceSpec.scala

Introduces a new page to the Catalogue at `/service/:name/costs` (linked to from the service info page) that shows a graph of estimated costs over time:

BDOG-1573 

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/FeatureSwitch.scala
app/uk/gov/hmrc/cataloguefrontend/SearchFiltering.scala
app/uk/gov/hmrc/cataloguefrontend/connector/TeamsAndRepositoriesConnector.scala
app/views/RepositoriesListPage.scala.html
app/views/partials/code_and_builds.scala.html
conf/application.conf
test/uk/gov/hmrc/cataloguefrontend/RepositoriesSpec.scala

BDOG-1677 Surface branch protection policies for repositories

---

app/uk/gov/hmrc/cataloguefrontend/leakdetection/LeakDetectionConnector.scala
app/views/leakdetection/LeakDetectionRepositoriesPage.scala.html
test/uk/gov/hmrc/cataloguefrontend/leakdetection/LeakDetectionServiceSpec.scala

BDOG-1846 - Identify repositories that are archived in LDS view

---

app/uk/gov/hmrc/cataloguefrontend/search/SearchIndex.scala
test/uk/gov/hmrc/cataloguefrontend/search/SearchIndexSpec.scala

1. Ensures that exact matches are always returned first, by increasing their weighting
2. Keeps SearchTerms belonging to the same service together by sorting on their name AFTER weighting.

BDOG-1939 Further improvements to Catalogue Search

---

app/views/ServiceConfigPage.scala.html
public/config-explorer.css

Allows text to overflow to a new line for environment columns

BDOG-1245: Adds Text Overflow

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/views/ServiceConfigPage.scala.html

Displays configs always for local and by deployed environment for all other envs

BDOG-1992 filter config display by deployed env

---

app/uk/gov/hmrc/cataloguefrontend/connector/model/BobbyRule.scala
app/views/partials/ModulesPartial.scala.html
app/views/partials/dependency_section.scala.html
app/views/teams/TeamInfoPage.scala.html
app/views/vulnerabilities/VulnerabilitiesListPage.scala.html

Just the fixes for the (hopefully) last 27 accessibility issues.

BDOG-2587: correct accessibility issues

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/FeatureSwitch.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ConfigConnector.scala
app/uk/gov/hmrc/cataloguefrontend/service/ConfigService.scala
app/views/ServiceConfigPage.scala.html
conf/application.conf
public/config-explorer.css
test/uk/gov/hmrc/cataloguefrontend/ServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/ConfigServiceSpec.scala

This is enabled with a feature flag, and handles incomplete deployment config data.

BDOG-2339 Show when config has changed but no been applied (by deployment)

---

app/uk/gov/hmrc/cataloguefrontend/service/ConfigService.scala
app/views/ServiceConfigPage.scala.html
test/uk/gov/hmrc/cataloguefrontend/service/ConfigServiceSpec.scala

Also fixes javascript bug for config keys containing chars invalid for ids

BDOG-2339 Fix showing latest keys not deployed when feature switch off

---

app/uk/gov/hmrc/cataloguefrontend/BobbyExplorerController.scala
app/uk/gov/hmrc/cataloguefrontend/serviceconfigs/ServiceConfigsController.scala
app/views/BobbyExplorerPage.scala.html
app/views/deployservice/DeployServicePage.scala.html
app/views/partials/dependency_section.scala.html
app/views/serviceconfigs/ConfigExplorerPage.scala.html
app/views/serviceconfigs/ConfigWarningPage.scala.html
app/views/serviceconfigs/SearchConfigPage.scala.html
conf/app.routes

Have run both accessibility and acceptance tests on these changes.

BDOG-2811: convert fragment to querystring selector param

---

app/views/partials/repo_owning_teams.scala.html

replaced plain text owner label with pill

---

app/views/partials/DependenciesByEnvironmentPartial.scala.html
project/plugins.sbt

The idea is to select the highest environment with a deployment, as in this examples:
Service A:
qa -> 0.5.0
staging -> 0.4.0
production -> 0.3.0    | SELECTED
Service B:
qa -> 0.5.0
staging -> 0.4.0 | SELECTED
Service C:
latest | SELECTED

BDOG-2879: Select highest environment with a deployment on service page

---

app/views/partials/RepoSearchResultsPage.scala.html

BDOG901 implement centering of branch protection indicators

---

app/uk/gov/hmrc/cataloguefrontend/users/model.scala
app/views/teams/TeamInfoPage.scala.html
app/views/users/UserInfoPage.scala.html
app/views/users/UserListPage.scala.html
test/uk/gov/hmrc/cataloguefrontend/connector/UserManagementConnectorSpec.scala

BDOG-2902: Add formatting for team roles in [TeamInfoPage, UserInfoPage, UserListPage]

---

app/uk/gov/hmrc/cataloguefrontend/users/model.scala

BDOG-2902: Revise displayName generation

---

app/uk/gov/hmrc/cataloguefrontend/config/CatalogueConfig.scala
app/uk/gov/hmrc/cataloguefrontend/shuttering/ShutterOverviewController.scala
conf/application.conf

- Also remove the banner for shuttering the whole of the rate platform as that option no longer exists

BDOG-3025: Update the URL for shuttering the whole platform

---

app/views/partials/tests.scala.html

Service repository no build info:
Service repository build info:

BDOG-3057: tests partiral expose datetime of run

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/views/ServiceInfoPage.scala.html
app/views/partials/decommissionErrorModal.scala.html
app/views/partials/decommissionWarnModal.scala.html
app/views/partials/details.scala.html

BDOG-3074: Always display details menu cog

---

app/uk/gov/hmrc/cataloguefrontend/servicecommissioningstatus/ServiceCommissioningStatusController.scala
app/views/servicecommissioningstatus/SearchServiceCommissioningStatusPage.scala.html

BDOG-3140: Add toggle group by Env for Search Commissioning State

---

app/uk/gov/hmrc/cataloguefrontend/servicecommissioningstatus/ServiceCommissioningStatusConnector.scala
app/uk/gov/hmrc/cataloguefrontend/servicecommissioningstatus/ServiceCommissioningStatusController.scala
app/uk/gov/hmrc/cataloguefrontend/servicecommissioningstatus/model.scala
app/views/servicecommissioningstatus/SearchServiceCommissioningStatusPage.scala.html
project/build.properties
public/catalogue-frontend.css

BDOG-3143: Surface warnings in search commissioning state

---

app/views/partials/RepoOwningTeamsHelper.scala
test/views/partials/RepoOwningTeamsHelperSpec.scala

Reverts hmrc/catalogue-frontend#889

Revert "BDOG-3138: include owning team to teams list"

---

app/views/servicecommissioningstatus/SearchServiceCommissioningStatusPage.scala.html

BDOG-3143: Change warning icon and reposition toggles

---

app/uk/gov/hmrc/cataloguefrontend/users/CreateUserController.scala
app/uk/gov/hmrc/cataloguefrontend/users/view/CreateUserPage.scala.html
conf/application.conf
test/uk/gov/hmrc/cataloguefrontend/createuser/CreateUserFormSpec.scala

- Add extra context around tooling when creating new user
- Disable unavailable tooling when creating user

BDOG-3280: Add handling for super_admin and all_team_admins when creating new user

---

app/uk/gov/hmrc/cataloguefrontend/serviceconfigs/view/ConfigExplorerPage.scala.html

BDOG-BAU config explorer - decode config key fragments to handle quotes

---

app/uk/gov/hmrc/cataloguefrontend/teams/view/TeamInfoPage.scala.html

* Validate that no repositories are owned by this team alone (The team must own either no repositories or repositories with multiple owners)

BDOG-3417: Add validation when deleting a team 

---

app/uk/gov/hmrc/cataloguefrontend/healthmetrics/HealthMetric.scala
app/uk/gov/hmrc/cataloguefrontend/healthmetrics/HealthMetricsConnector.scala
app/uk/gov/hmrc/cataloguefrontend/healthmetrics/HealthMetricsController.scala
app/uk/gov/hmrc/cataloguefrontend/healthmetrics/model.scala
app/uk/gov/hmrc/cataloguefrontend/healthmetrics/view/HealthMetricsTimelinePage.scala.html
app/uk/gov/hmrc/cataloguefrontend/teams/TeamsController.scala
app/uk/gov/hmrc/cataloguefrontend/teams/view/DigitalServicePage.scala.html
app/uk/gov/hmrc/cataloguefrontend/teams/view/TeamInfoPage.scala.html
app/uk/gov/hmrc/cataloguefrontend/teams/view/healthPartial.scala.html
app/uk/gov/hmrc/cataloguefrontend/teams/view/shutteringPartial.scala.html
build.sbt
conf/app.routes
conf/application.conf
test/uk/gov/hmrc/cataloguefrontend/teams/TeamsControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/test/FakeApplicationBuilder.scala

- Adds health metrics timeline page to display health metric counts over time
- Refactors health cards to use new health-metrics service

BDOG-3397: health metrics timeline

---

app/uk/gov/hmrc/cataloguefrontend/view/JdkAcrossEnvironmentsPage.scala.html

Ticket: [https://jira.tools.tax.service.gov.uk/browse/BDOG-3540](https://jira.tools.tax.service.gov.uk/browse/BDOG-3540)
Desc: Selected team on the jdkexplorer page should remain selected.

BDOG-3540 - Ensure selected team on JDKExplorer page sticks
