app/views/landing_page.scala.html

Libraries weren't in the original release (and possessive "its" has no apostrophe)

Add libraries and fix typo

---

app/assets/catalogue-frontend.scss
app/views/repositories_list.scala.html
public/catalogue-frontend.css

This PR contains a few tweaks around the search filter. 
IMO a little more work is needed around the functionality of the filter/search. As @eisenhower444 pointed out the `Type:` row could potentially be removed.
- Update Html to be more semantic
- Add `autofocus` to name input
- Add more bootstrap styles
- Remove type row for the moment
- Make filter/search work `onChange`

Search filter tweaks

---

conf/application.conf

Also see: 
https://github.com/hmrc/app-config-platapps-labs/pull/9
https://github.com/hmrc/app-config-base/pull/1345

BDOG-33 removed play.ws.ssl.loose.acceptAnyCertificate setting

---

app/uk/gov/hmrc/cataloguefrontend/FeatureSwitch.scala
app/views/ServiceInfoPage.scala.html
app/views/TeamInfoPage.scala.html
test/uk/gov/hmrc/cataloguefrontend/ServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/TeamServicesSpec.scala

Following the decision that the indicators are probably useless and that no one is probably using them, this PR removes them from view.

PLATOPS-154 Toggling off indicator graphs

---

app/uk/gov/hmrc/cataloguefrontend/BobbyExplorerController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ConfigConnector.scala
app/uk/gov/hmrc/cataloguefrontend/connector/model/BobbyRule.scala
app/uk/gov/hmrc/cataloguefrontend/service/BobbyService.scala
app/uk/gov/hmrc/cataloguefrontend/service/model/BobbyRulesView.scala
app/views/BobbyExplorerPage.scala.html
app/views/standard_layout.scala.html
conf/app.routes
public/catalogue-frontend.css
test/uk/gov/hmrc/cataloguefrontend/connector/model/BobbyRuleFactory.scala
test/uk/gov/hmrc/cataloguefrontend/connector/model/BobbyRuleSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/BobbyServiceSpec.scala

Displays list of all Bobby rules, in Upcoming and Active sections.
Note that the controller retrieves the results from service-configs each time this URL is accessed - the results are not cached.  A network error will simply display the generic "An error has occurred" page.

BDOG-182 Bobby Explorer

---

app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model.scala
app/views/WhatsRunningWherePage.scala.html
conf/app.routes
conf/application.conf
test/uk/gov/hmrc/cataloguefrontend/WhatsRunningWhereSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ReleasesConnectorSpec.scala

Porting the What's Running Where from the old releases app to the
Catalogue. This is a first commit; more will come to address all the
points in the ticket. For instance, filtering is only available via
query params, and there is no link to the page on the menu yet.
I have attached a screenshot of it to the JIRA.

BDOG-447: Basic What's Running Where

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/ServiceInfoView.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ServiceDependenciesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/connector/model/Dependencies.scala
app/views/ServiceConfigPage.scala.html
app/views/ServiceInfoPage.scala.html
app/views/partials/BuildToolsPartial.scala.html
app/views/partials/DependenciesByEnvironmentPartial.scala.html
app/views/partials/ServiceDependenciesPartial.scala.html
public/catalogue-frontend.css
test/uk/gov/hmrc/cataloguefrontend/ServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ServiceDependenciesConnectorSpec.scala

Add a tabbed section to the service page, and move library dependencies & service urls (such as Kibana / Grafana) into the tab - so that the information displayed relates to the selected environment / deployed version of the service in that environment.
Note that the platform dependencies displayed on the "latest" tab are sourced from master (as at present) i.e. they are not sourced from a slug, whereas the dependencies displayed on all other tabs are pulled from the slug relating to the version of the service deployed in that environment.

BDOG-446: service page - environments as tabs with version-specific dependencies

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ServiceDependenciesConnector.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ServiceDependenciesConnectorSpec.scala

Populate the 'Platform Dependencies' section on the 'Latest' tab of a Service page from slug info dependencies rather than the parsing of master / GitHub.  This brings 'Latest' into line with the datasource of the other tabs (albeit they target a specific slug version rather than slug flag).

BDOG-525: Populate Platform Dependencies on Latest service page tab from slug

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/ServiceInfoView.scala
app/views/ServiceInfoPage.scala.html
app/views/partials/BuildToolsPartial.scala.html
app/views/partials/DependenciesByEnvironmentPartial.scala.html
app/views/partials/ServiceDependenciesPartial.scala.html
app/views/partials/dependency_section.scala.html
conf/messages

Assume that library dependencies derived from parsing build files on master that are not known to the appropriate "latest" tagged "slug-info" represent "test-only" library dependencies.  Examples are typically _reactivemongo-test_ and _hmrctest_.  Add such dependencies to what was previously called the "Build Tools" section under the heading "Test libraries", and rename the section to "Latest Build" (as it is no longer just about "tools").
Sort the display of dependencies by name - they are currently displayed in the order retrieved from the database.

Bdog 525 test dependencies

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/views/partials/DependenciesByEnvironmentPartial.scala.html
test/uk/gov/hmrc/cataloguefrontend/CatalogueControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DigitalServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/LibrariesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/PrototypesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServiceOwnerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicesSpec.scala

The Jenkins link in the "services" array exposed by teams-and-repositories "respositoryDetails" is a link to deploy-microservice which is not service specific.  This should not be displayed on the Service Page in the "Telemetry" section - which should contain only links to Grafana & Kibana (which are tailored for the relevant service & environment).
Note that these links are driven by teams-and-repositories config, and so we must allow the target link name to also be configured in catalogue-frontend.  If no such config is defined we fall back to a sensible default (the current value).

BDOG-528: remove Jenkins from displayed telemetry links

---

app/uk/gov/hmrc/cataloguefrontend/DateHelper.scala
app/views/shuttering/ShutterOverviewPage.scala.html
conf/messages
public/catalogue-frontend.css

* add appropriate link to shutter event history if there is at least one shutter event, else display 'No events'
* change the displayed username on auto-reconciliation events from 'shutter-api' to '<outside the catalogue>'
* also fixes issue where timestamps had incorrect values for the seconds component

BDOG-481: add links to Shutter Event History from Shutter Overview

---

app/uk/gov/hmrc/cataloguefrontend/BobbyRulesTrendController.scala
app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/DateHelper.scala
app/uk/gov/hmrc/cataloguefrontend/DependencyExplorerController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/model/Dependencies.scala
app/uk/gov/hmrc/cataloguefrontend/shuttering/ShutterWizardController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/DeploymentHistoryController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/FuturePlatformMigrationController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnector.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/model.scala
app/views/DeploymentHistoryPage.scala.html
app/views/RepositoriesListPage.scala.html
app/views/shuttering/ShutterOverviewPage.scala.html
app/views/standard_layout.scala.html
app/views/whatsrunningwhere/WhatsRunningWherePage.scala.html
build.sbt
conf/app.routes
conf/application.conf
project/build.properties
project/plugins.sbt
test/uk/gov/hmrc/cataloguefrontend/DeploymentHistoryControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DeploymentsFilterSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/DeploymentSpec.scala

1. Deployment page now pulls both ECS and heritage data out of `releases-api`. There is still a single page view for both, but ECS releases have a badge next to them
1. Page now shows data for all environments (not just Production) as before, on separate tabs
1. Improved the form by adding type-a-head search, sorting, and auto reloading
1. Now shows all deployments for a given version, not just the first time a particular version was seen, as was the case before (i.e. previously multiple deployments of the same version would only show once, for the original deployment)
1. Also added sorting to the shuttering overview and repository pages

BDOG-591 add ECS deployments to deployments page

---

app/views/partials/code_and_builds.scala.html
test/view/partials/CodeAndBuildsSpec.scala

As well as not being checked by the compiler, the links could break if the page was loaded with an additional `/`
e.g. `/service/myservice/` leads to `/service/myservice/myservice/conf` rather than `/service/myservice/conf`

Fix links for trailing slash

---

app/uk/gov/hmrc/cataloguefrontend/DependenciesController.scala
app/uk/gov/hmrc/cataloguefrontend/healthindicators/HealthIndicatorsConnector.scala
app/uk/gov/hmrc/cataloguefrontend/healthindicators/HealthIndicatorsController.scala
app/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereController.scala
app/views/HealthIndicatorsPage.scala.html
conf/app.routes
conf/application.conf
public/catalogue-frontend.css
test/uk/gov/hmrc/cataloguefrontend/DependencyReportControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DeploymentHistoryControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DigitalServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/DigitalServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/FakeApplicationBuilder.scala
test/uk/gov/hmrc/cataloguefrontend/FrontendRouteWarningsPageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/LibraryPageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/PrototypePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/RepositoriesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/RepositoryPageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/TeamServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/TeamsSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ShutterGroupsConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/TeamsAndRepositoriesConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/healthindicators/HealthIndicatorsConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/healthindicators/HealthIndicatorsControllerSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/ReleasesConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/whatsrunningwhere/WhatsRunningWhereSpec.scala

This is a rough first draft of the service health indicators page for a repo, nothing here is set in stone and would appreciate feed back on the code and UI.
I have kept the new page on a test endpoint as it won't be linked to through the nav bar for the time being. 
Screen shot of added page: https://user-images.githubusercontent.com/68235822/107976182-12c92a00-6fb1-11eb-92a9-45602e132f4d.png

adds basic display page for repo health indicators + connector + testing

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/connector/ConfigConnector.scala
app/uk/gov/hmrc/cataloguefrontend/service/CostEstimationService.scala
app/uk/gov/hmrc/cataloguefrontend/util/CurrencyFormatter.scala
app/views/ServiceInfoPage.scala.html
app/views/partials/costEstimation.scala.html
test/uk/gov/hmrc/cataloguefrontend/DigitalServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/LibrariesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/PrototypesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/connector/ConfigConnectorSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/CostEstimationServiceSpec.scala

Estimated yearly cost (total ~slots~ instances across all environments * ~£650.00~ $120) is now displayed on the `ServiceInfoPage`, e.g. on `/repositories/repository-name` where `repository-name` is the name of a service.
Here's an example view:
--
I've still not been able to spin this up locally with an export of the Mongo DB in order to kick the tyres properly, so I'll hold off on merging this until I can do that (waiting for an automated job to fire tomorrow morning to finalise my access.)

Provide service cost estimates

---

app/views/partials/costEstimation.scala.html

Cost estimation is no longer based on slot usage, but on instance usage.
This change updates the explaining text in the relevant view
accordingly.

Fix cost estimation wording

---

app/uk/gov/hmrc/cataloguefrontend/CatalogueController.scala
app/uk/gov/hmrc/cataloguefrontend/service/CostEstimationService.scala
app/views/ServiceInfoPage.scala.html
app/views/partials/costEstimation.scala.html
test/uk/gov/hmrc/cataloguefrontend/DigitalServicePageSpec.scala
test/uk/gov/hmrc/cataloguefrontend/LibrariesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/PrototypesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/ServicesSpec.scala
test/uk/gov/hmrc/cataloguefrontend/service/CostEstimationServiceSpec.scala

Looks a little something like this:

Cost estimates include per-environment breakdowns

---

public/catalogue-frontend.css

Applies the fix detailed here:
https://github.com/google/google-visualization-issues/issues/2162

BDOG-1573 Fix chart flickering in Chrome

---

app/views/error_403_template.scala.html
app/views/error_404_template.scala.html
app/views/error_template.scala.html
app/views/partials/with_username.scala.html
app/views/standard_layout.scala.html

It's not required, and the body is not actually available for error templates

BAU Replace Request with RequestHeader in view templates

---

app/views/vulnerabilities/VulnerabilitiesListPage.scala.html

A hidden form submit button is required due to having 2 different text search inputs - otherwise the enter button will not submit the form. However 'display-none' does not work in Safari, so using the visibility attribute instead. Tested in Chrome, Safari and Firefox.

BDOG-2036 Fix bug which prevented form submission in Safari

---

app/views/vulnerabilities/VulnerabilitiesListPage.scala.html
app/views/vulnerabilities/VulnerabilityDetails.scala.html

1. The table on this page consists of `groups` of two rows, the first is visible by default, and the second is expandable. List.js respects the sorting order for columns with one word (vuln-id), or numbers (score, teams, services). However when sorting on description or component path, the hidden child row would sometimes be sorted above the parent row, so when expanded, it would jump above. We don't need to sort by these columns anyway, so have removed from list.js config.
2. Changed nested table from striped to white, to make it easier to distinguish between an expanded section and the next row.

BDOG-2036: Fix sorting bug, and change nested table colour.

---

app/views/vulnerabilities/VulnerabilitiesListPage.scala.html

Currently only certain columns show the hand-pointer when hovering over, meaning only certain columns can expand the collapsable row. This is inconsistent. Desired behaviour is that clicking anywhere on the parent row should expand the child row.

BDOG-2036 Fix CSS

---

app/views/partials/service_relationships.scala.html
public/catalogue-frontend.css
public/catalogue-frontend.js

The `Services Relationship` section on the [Service Catalogue](https://catalogue.tax.service.gov.uk/repositories/auth#service_relationships) page need to be presented in a way that, when truncation happens, it needs to be obvious to our users.
These changes involve applying a gradient mask to the related services lists and, also, the replacement of text with icons on the links that applies and removes the truncation.

BDOG-2553: clarify truncated service relationship section

---

app/views/BobbyExplorerPage.scala.html
app/views/DependencyExplorerPage.scala.html
app/views/DeploymentHistoryPage.scala.html
app/views/HealthIndicatorsLeaderBoard.scala.html
app/views/RepositoriesListPage.scala.html
app/views/leakdetection/LeakDetectionDraftPage.scala.html
app/views/leakdetection/LeakDetectionExemptionsPage.scala.html
app/views/leakdetection/LeakDetectionLeaksPage.scala.html
app/views/leakdetection/LeakDetectionRepositoriesPage.scala.html
app/views/leakdetection/LeakDetectionRepositoryPage.scala.html
app/views/prcommenter/PrCommenterRecommendationsPage.scala.html
app/views/shuttering/ShutterOverviewPage.scala.html
app/views/teams/teams_list.scala.html
app/views/vulnerabilities/VulnerabilitiesListPage.scala.html
public/catalogue-frontend.css

It's pretty much adding the `sticky-header` class from the config search changes, except for the change in `Dependency Explorer`.
https://jira.tools.tax.service.gov.uk/secure/attachment/568828/568828_sticky+column+dependency+explorer.webm

BDOG-2660: Add sticky column to catalogue pages
